### PR TITLE
Feature: Upgrade Board Size

### PR DESCRIPTION
**Pull request by Megha-Dev-19**

### CODE REVIEW

**Comment by Calcifer1001** [comment]
I've run it and wasn't able to even create a game. The page is loading quite slow and my computer's fan started to run a lot. Were you able to run it properly?

**Comment by Calcifer1001** [comment]
I had this error displaying. As long as I didn't do something, I wasn't able to click anything. Do you have it as well? Let's solve it properly before doing anything. 

image

**Comment by Calcifer1001** [comment]
Check for these cases you don't need the short if. Reading the find documentation, you can see either returns an object or undefined. In js, the way to solve these this is to put !! like a double negation. If you negate undefined, it's true, so another negation is false. If you negate something, it becames false, so negating again becames true

image

**Comment by Calcifer1001** [comment]
There are better ways to do this. In this case it's hard to notice if you mean 5 Cheddar, 50 Cheddar or 500 Cheddar. Take advantage of the repeat function like: "50" + "0".repeat(24). This way it's clear we're talking about 50 cheddar

image

**Comment by Megha-Dev-19** [comment]
> I had this error displaying. As long as I didn't do something, I wasn't able to click anything. Do you have it as well? Let's solve it properly before doing anything.
> 
> image

I don't get this error

**Pull request merged**
